name: PermissionsSystem
main: de.philippcmd.permissions-system.Main
version: 1.0.0
api-version: '1.20.1'
author: philippcmd

commands:
  permission:
    description: manages permissions of players
    usage: /permission <give|remove> <permission> <player>
    aliases: ["perm"]
    permission: permissions.manage
    permission-message: You have no permission to run this command